package it.webred.cs.csa.ejb.enumeratori;

public enum SiruEnum {

	ATECO,
	DIMENSIONE_AZIENDA,
	FORMA_GIURIDICA_RNA,
	GRUPPO_VUL_PART,
	IT_COMUNE,
	IT_NAZIONE,
	LOCALIZZAZIONE_GEOG,
	STATO_PARTECIPANTE,
	TIPO_ORARIO_LAVORO,
	TIPOLOGIA_LAVORO,
	TITOLO_STUDIO,
	DURATA_RICERCA,
	CITTADINANZA,
	CONDIZIONE_MERCATO,
	SISO_NAZIONE,
	SISO_ATECO,
	RESIDENZA;	
}
