package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArCFonteinfo generated by hbm2java
 */
@Entity
@Table(name = "AR_C_FONTEINFO")
public class ArCFonteinfo implements java.io.Serializable {

	private long id;
	private String descrizione;
	private BigDecimal amTipoinfoFkAmFonte;
	private String amTimoinfoInformazione;
	private String tooltip;
	private Character abilitato;
	private Set<ArDato> arDatos = new HashSet<ArDato>(0);

	public ArCFonteinfo() {
	}

	public ArCFonteinfo(long id) {
		this.id = id;
	}

	public ArCFonteinfo(long id, String descrizione,
			BigDecimal amTipoinfoFkAmFonte, String amTimoinfoInformazione,
			String tooltip, Character abilitato, Set<ArDato> arDatos) {
		this.id = id;
		this.descrizione = descrizione;
		this.amTipoinfoFkAmFonte = amTipoinfoFkAmFonte;
		this.amTimoinfoInformazione = amTimoinfoInformazione;
		this.tooltip = tooltip;
		this.abilitato = abilitato;
		this.arDatos = arDatos;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "DESCRIZIONE", length = 100)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "AM_TIPOINFO_FK_AM_FONTE", precision = 22, scale = 0)
	public BigDecimal getAmTipoinfoFkAmFonte() {
		return this.amTipoinfoFkAmFonte;
	}

	public void setAmTipoinfoFkAmFonte(BigDecimal amTipoinfoFkAmFonte) {
		this.amTipoinfoFkAmFonte = amTipoinfoFkAmFonte;
	}

	@Column(name = "AM_TIMOINFO_INFORMAZIONE", length = 2000)
	public String getAmTimoinfoInformazione() {
		return this.amTimoinfoInformazione;
	}

	public void setAmTimoinfoInformazione(String amTimoinfoInformazione) {
		this.amTimoinfoInformazione = amTimoinfoInformazione;
	}

	@Column(name = "TOOLTIP", length = 4000)
	public String getTooltip() {
		return this.tooltip;
	}

	public void setTooltip(String tooltip) {
		this.tooltip = tooltip;
	}

	@Column(name = "ABILITATO", length = 1)
	public Character getAbilitato() {
		return this.abilitato;
	}

	public void setAbilitato(Character abilitato) {
		this.abilitato = abilitato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arCFonteinfo")
	public Set<ArDato> getArDatos() {
		return this.arDatos;
	}

	public void setArDatos(Set<ArDato> arDatos) {
		this.arDatos = arDatos;
	}

}
