package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArCsSoggettoCs generated by hbm2java
 */
@Entity
@Table(name = "AR_CS_SOGGETTO_CS")
public class ArCsSoggettoCs implements java.io.Serializable {

	private long id;
	private ArCsSoggettoCs arCsSoggettoCs;
	private ArCsDatoCs arCsDatoCs;
	private String idOrig;
	private String denominazione;
	private String ente;
	private String note;
	private long TTiposoggId;
	private String indirizzo;
	private String tel;
	private String fax;
	private String email;
	private String userIns;
	private Date dtIns;
	private String usrMod;
	private Date dtMod;
	private Set<ArCsSoggettoCs> arCsSoggettoCses = new HashSet<ArCsSoggettoCs>(
			0);
	private Set<ArCsTrasfFondi> arCsTrasfFondis = new HashSet<ArCsTrasfFondi>(0);
	private Set<ArCsDatoCs> arCsDatoCses = new HashSet<ArCsDatoCs>(0);

	public ArCsSoggettoCs() {
	}

	public ArCsSoggettoCs(long id, ArCsDatoCs arCsDatoCs, String denominazione,
			long TTiposoggId, String userIns, Date dtIns) {
		this.id = id;
		this.arCsDatoCs = arCsDatoCs;
		this.denominazione = denominazione;
		this.TTiposoggId = TTiposoggId;
		this.userIns = userIns;
		this.dtIns = dtIns;
	}

	public ArCsSoggettoCs(long id, ArCsSoggettoCs arCsSoggettoCs,
			ArCsDatoCs arCsDatoCs, String idOrig, String denominazione,
			String ente, String note, long TTiposoggId, String indirizzo,
			String tel, String fax, String email, String userIns, Date dtIns,
			String usrMod, Date dtMod, Set<ArCsSoggettoCs> arCsSoggettoCses,
			Set<ArCsTrasfFondi> arCsTrasfFondis, Set<ArCsDatoCs> arCsDatoCses) {
		this.id = id;
		this.arCsSoggettoCs = arCsSoggettoCs;
		this.arCsDatoCs = arCsDatoCs;
		this.idOrig = idOrig;
		this.denominazione = denominazione;
		this.ente = ente;
		this.note = note;
		this.TTiposoggId = TTiposoggId;
		this.indirizzo = indirizzo;
		this.tel = tel;
		this.fax = fax;
		this.email = email;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.usrMod = usrMod;
		this.dtMod = dtMod;
		this.arCsSoggettoCses = arCsSoggettoCses;
		this.arCsTrasfFondis = arCsTrasfFondis;
		this.arCsDatoCses = arCsDatoCses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOGGETTO_CS_ID")
	public ArCsSoggettoCs getArCsSoggettoCs() {
		return this.arCsSoggettoCs;
	}

	public void setArCsSoggettoCs(ArCsSoggettoCs arCsSoggettoCs) {
		this.arCsSoggettoCs = arCsSoggettoCs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DATO_CS_ID", nullable = false)
	public ArCsDatoCs getArCsDatoCs() {
		return this.arCsDatoCs;
	}

	public void setArCsDatoCs(ArCsDatoCs arCsDatoCs) {
		this.arCsDatoCs = arCsDatoCs;
	}

	@Column(name = "ID_ORIG", length = 70)
	public String getIdOrig() {
		return this.idOrig;
	}

	public void setIdOrig(String idOrig) {
		this.idOrig = idOrig;
	}

	@Column(name = "DENOMINAZIONE", nullable = false)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	@Column(name = "ENTE", length = 5)
	public String getEnte() {
		return this.ente;
	}

	public void setEnte(String ente) {
		this.ente = ente;
	}

	@Column(name = "NOTE", length = 3000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "T_TIPOSOGG_ID", nullable = false, precision = 10, scale = 0)
	public long getTTiposoggId() {
		return this.TTiposoggId;
	}

	public void setTTiposoggId(long TTiposoggId) {
		this.TTiposoggId = TTiposoggId;
	}

	@Column(name = "INDIRIZZO", length = 100)
	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	@Column(name = "TEL", length = 100)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "FAX", length = 100)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "USER_INS", nullable = false, length = 50)
	public String getUserIns() {
		return this.userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", nullable = false, length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "USR_MOD", length = 50)
	public String getUsrMod() {
		return this.usrMod;
	}

	public void setUsrMod(String usrMod) {
		this.usrMod = usrMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MOD", length = 7)
	public Date getDtMod() {
		return this.dtMod;
	}

	public void setDtMod(Date dtMod) {
		this.dtMod = dtMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arCsSoggettoCs")
	public Set<ArCsSoggettoCs> getArCsSoggettoCses() {
		return this.arCsSoggettoCses;
	}

	public void setArCsSoggettoCses(Set<ArCsSoggettoCs> arCsSoggettoCses) {
		this.arCsSoggettoCses = arCsSoggettoCses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arCsSoggettoCs")
	public Set<ArCsTrasfFondi> getArCsTrasfFondis() {
		return this.arCsTrasfFondis;
	}

	public void setArCsTrasfFondis(Set<ArCsTrasfFondi> arCsTrasfFondis) {
		this.arCsTrasfFondis = arCsTrasfFondis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arCsSoggettoCs")
	public Set<ArCsDatoCs> getArCsDatoCses() {
		return this.arCsDatoCses;
	}

	public void setArCsDatoCses(Set<ArCsDatoCs> arCsDatoCses) {
		this.arCsDatoCses = arCsDatoCses;
	}

}
