package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArDato generated by hbm2java
 */
@Entity
@Table(name = "AR_DATO")
public class ArDato implements java.io.Serializable {

	private long id;
	private ArCFonteinfo arCFonteinfo;
	private ArPeriodo arPeriodo;
	private ArSpazio arSpazio;
	private Date dataAggiornamento;
	private String userIns;
	private Date dtIns;
	private String usrMod;
	private Date dtMod;
	private Set<ArCsDatoCs> arCsDatoCses = new HashSet<ArCsDatoCs>(0);

	public ArDato() {
	}

	public ArDato(long id, ArCFonteinfo arCFonteinfo, ArPeriodo arPeriodo,
			Date dataAggiornamento, String userIns, Date dtIns) {
		this.id = id;
		this.arCFonteinfo = arCFonteinfo;
		this.arPeriodo = arPeriodo;
		this.dataAggiornamento = dataAggiornamento;
		this.userIns = userIns;
		this.dtIns = dtIns;
	}

	public ArDato(long id, ArCFonteinfo arCFonteinfo, ArPeriodo arPeriodo,
			ArSpazio arSpazio, Date dataAggiornamento, String userIns,
			Date dtIns, String usrMod, Date dtMod, Set<ArCsDatoCs> arCsDatoCses) {
		this.id = id;
		this.arCFonteinfo = arCFonteinfo;
		this.arPeriodo = arPeriodo;
		this.arSpazio = arSpazio;
		this.dataAggiornamento = dataAggiornamento;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.usrMod = usrMod;
		this.dtMod = dtMod;
		this.arCsDatoCses = arCsDatoCses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FONTEINFO_ID", nullable = false)
	public ArCFonteinfo getArCFonteinfo() {
		return this.arCFonteinfo;
	}

	public void setArCFonteinfo(ArCFonteinfo arCFonteinfo) {
		this.arCFonteinfo = arCFonteinfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERIODO_ID", nullable = false)
	public ArPeriodo getArPeriodo() {
		return this.arPeriodo;
	}

	public void setArPeriodo(ArPeriodo arPeriodo) {
		this.arPeriodo = arPeriodo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPAZIO_ID")
	public ArSpazio getArSpazio() {
		return this.arSpazio;
	}

	public void setArSpazio(ArSpazio arSpazio) {
		this.arSpazio = arSpazio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_AGGIORNAMENTO", nullable = false, length = 7)
	public Date getDataAggiornamento() {
		return this.dataAggiornamento;
	}

	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	@Column(name = "USER_INS", nullable = false, length = 50)
	public String getUserIns() {
		return this.userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", nullable = false, length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "USR_MOD", length = 50)
	public String getUsrMod() {
		return this.usrMod;
	}

	public void setUsrMod(String usrMod) {
		this.usrMod = usrMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MOD", length = 7)
	public Date getDtMod() {
		return this.dtMod;
	}

	public void setDtMod(Date dtMod) {
		this.dtMod = dtMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arDato")
	public Set<ArCsDatoCs> getArCsDatoCses() {
		return this.arCsDatoCses;
	}

	public void setArCsDatoCses(Set<ArCsDatoCs> arCsDatoCses) {
		this.arCsDatoCses = arCsDatoCses;
	}

}
