package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArFfLineafin generated by hbm2java
 */
@Entity
@Table(name = "AR_FF_LINEAFIN")
public class ArFfLineafin implements java.io.Serializable {

	@Id
	@SequenceGenerator(name="AR_LINEA_FIN_ID_GENERATOR", sequenceName="SQ_ID",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="AR_LINEA_FIN_ID_GENERATOR")
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROGETTO_ID")
	private ArFfProgetto arFfProgetto;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FONDO_ID", nullable = false)
	private ArFfFondo arFfFondo;
	
	@Column(name = "CODICE_MEMO", nullable = false, length = 20)
	private String codiceMemo;
	
	@Column(name = "DESCRIZIONE", nullable = false)
	private String descrizione;
	
	@Column(name = "USER_INS", nullable = false, length = 50)
	private String userIns;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", nullable = false, length = 7)
	private Date dtIns;
	
	@Column(name = "USR_MOD", length = 50)
	private String usrMod;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MOD", length = 7)
	private Date dtMod;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_INIZIO_VAL", nullable = false, length = 7)
	private Date dataInizioVal;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FINE_VAL", nullable = false, length = 7)
	private Date dtFineVal;
	
	private BigDecimal importo;
	
	private Boolean abilitato;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arFfLineafin")
	private Set<ArFfServizio> arFfServizios = new HashSet<ArFfServizio>(0);

	public ArFfLineafin() {
	}

	public ArFfLineafin(long id, ArFfFondo arFfFondo, String codiceMemo,
			String descrizione, String userIns, Date dtIns, Date dataInizioVal,
			Date dtFineVal, BigDecimal importo) {
		this.id = id;
		this.arFfFondo = arFfFondo;
		this.codiceMemo = codiceMemo;
		this.descrizione = descrizione;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.dataInizioVal = dataInizioVal;
		this.dtFineVal = dtFineVal;
		this.importo = importo;
	}

	public ArFfLineafin(long id, ArFfProgetto arFfProgetto,
			ArFfFondo arFfFondo, String codiceMemo, String descrizione,
			String userIns, Date dtIns, String usrMod, Date dtMod,
			Boolean abilitato, Date dataInizioVal, Date dtFineVal,
			BigDecimal importo, Set<ArFfServizio> arFfServizios) {
		this.id = id;
		this.arFfProgetto = arFfProgetto;
		this.arFfFondo = arFfFondo;
		this.codiceMemo = codiceMemo;
		this.descrizione = descrizione;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.usrMod = usrMod;
		this.dtMod = dtMod;
		this.abilitato = abilitato;
		this.dataInizioVal = dataInizioVal;
		this.dtFineVal = dtFineVal;
		this.importo = importo;
		this.arFfServizios = arFfServizios;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public ArFfProgetto getArFfProgetto() {
		return this.arFfProgetto;
	}

	public void setArFfProgetto(ArFfProgetto arFfProgetto) {
		this.arFfProgetto = arFfProgetto;
	}

	public ArFfFondo getArFfFondo() {
		return this.arFfFondo;
	}

	public void setArFfFondo(ArFfFondo arFfFondo) {
		this.arFfFondo = arFfFondo;
	}

	public String getCodiceMemo() {
		return this.codiceMemo;
	}

	public void setCodiceMemo(String codiceMemo) {
		this.codiceMemo = codiceMemo;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getUserIns() {
		return this.userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	public String getUsrMod() {
		return this.usrMod;
	}

	public void setUsrMod(String usrMod) {
		this.usrMod = usrMod;
	}

	public Date getDtMod() {
		return this.dtMod;
	}

	public void setDtMod(Date dtMod) {
		this.dtMod = dtMod;
	}

	public Date getDataInizioVal() {
		return this.dataInizioVal;
	}

	public void setDataInizioVal(Date dataInizioVal) {
		this.dataInizioVal = dataInizioVal;
	}

	public Date getDtFineVal() {
		return this.dtFineVal;
	}

	public void setDtFineVal(Date dtFineVal) {
		this.dtFineVal = dtFineVal;
	}

	@Column(name = "IMPORTO", nullable = false, precision = 20)
	public BigDecimal getImporto() {
		return this.importo;
	}

	public void setImporto(BigDecimal importo) {
		this.importo = importo;
	}

	public Set<ArFfServizio> getArFfServizios() {
		return this.arFfServizios;
	}

	public void setArFfServizios(Set<ArFfServizio> arFfServizios) {
		this.arFfServizios = arFfServizios;
	}

	public Boolean getAbilitato() {
		return abilitato;
	}

	public void setAbilitato(Boolean abilitato) {
		this.abilitato = abilitato;
	}

}
