package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArFfFondo generated by hbm2java
 */
@Entity
@Table(name = "AR_FF_FONDO")
@NamedQuery(name="ArFfFondo.findAll", query="SELECT c FROM ArFfFondo c")
public class ArFfFondo implements java.io.Serializable {

	@Id
	private long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORIGINE_ID", nullable = false)
	private ArFfTbOrigine arFfTbOrigine;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAPOFILA_ORGANIZZAZIONE_ID", nullable = false)
	private ArOOrganizzazione arOOrganizzazione;
	
	@Column(name = "CODICE_MEMO", nullable = false, length = 20)
	private String codiceMemo;
	
	private String descrizione;
	
	@Column(name = "USER_INS", length = 50)
	private String userIns;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", length = 7)
	private Date dtIns;
	
	@Column(name = "USR_MOD", length = 50)
	private String usrMod;

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MOD", length = 7)
	private Date dtMod;
	
	
	private Boolean abilitato;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_INIZIO_VAL", nullable = false, length = 7)
	private Date dataInizioVal;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FINE_VAL", nullable = false, length = 7)
	private Date dtFineVal;
	
	private BigDecimal importo;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arFfFondo")
	private Set<ArFfLineafin> arFfLineafins = new HashSet<ArFfLineafin>(0);

	public ArFfFondo() {
	}

	public ArFfFondo(long id, ArFfTbOrigine arFfTbOrigine,
			ArOOrganizzazione arOOrganizzazione, String codiceMemo,
			String descrizione, String userIns, Date dtIns, Date dataInizioVal,
			Date dtFineVal, BigDecimal importo, boolean flagDirettoZona) {
		this.id = id;
		this.arFfTbOrigine = arFfTbOrigine;
		this.arOOrganizzazione = arOOrganizzazione;
		this.codiceMemo = codiceMemo;
		this.descrizione = descrizione;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.dataInizioVal = dataInizioVal;
		this.dtFineVal = dtFineVal;
		this.importo = importo;
	}

	public ArFfFondo(long id, ArFfTbOrigine arFfTbOrigine,
			ArOOrganizzazione arOOrganizzazione, String codiceMemo,
			String descrizione, String userIns, Date dtIns, String usrMod,
			Date dtMod, Boolean abilitato, Date dataInizioVal,
			Date dtFineVal, BigDecimal importo,
			Set<ArFfLineafin> arFfLineafins) {
		this.id = id;
		this.arFfTbOrigine = arFfTbOrigine;
		this.arOOrganizzazione = arOOrganizzazione;
		this.codiceMemo = codiceMemo;
		this.descrizione = descrizione;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.usrMod = usrMod;
		this.dtMod = dtMod;
		this.abilitato = abilitato;
		this.dataInizioVal = dataInizioVal;
		this.dtFineVal = dtFineVal;
		this.importo = importo;
		this.arFfLineafins = arFfLineafins;
	}


	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	
	public ArFfTbOrigine getArFfTbOrigine() {
		return this.arFfTbOrigine;
	}

	public void setArFfTbOrigine(ArFfTbOrigine arFfTbOrigine) {
		this.arFfTbOrigine = arFfTbOrigine;
	}

	public ArOOrganizzazione getArOOrganizzazione() {
		return this.arOOrganizzazione;
	}

	public void setArOOrganizzazione(ArOOrganizzazione arOOrganizzazione) {
		this.arOOrganizzazione = arOOrganizzazione;
	}

	
	public String getCodiceMemo() {
		return this.codiceMemo;
	}

	public void setCodiceMemo(String codiceMemo) {
		this.codiceMemo = codiceMemo;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}
	
	public String getUserIns() {
		return this.userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	public String getUsrMod() {
		return this.usrMod;
	}

	public void setUsrMod(String usrMod) {
		this.usrMod = usrMod;
	}

	public Date getDtMod() {
		return this.dtMod;
	}

	public void setDtMod(Date dtMod) {
		this.dtMod = dtMod;
	}

	public Date getDataInizioVal() {
		return this.dataInizioVal;
	}

	public void setDataInizioVal(Date dataInizioVal) {
		this.dataInizioVal = dataInizioVal;
	}

	public Date getDtFineVal() {
		return this.dtFineVal;
	}

	public void setDtFineVal(Date dtFineVal) {
		this.dtFineVal = dtFineVal;
	}

	public BigDecimal getImporto() {
		return this.importo;
	}

	public void setImporto(BigDecimal importo) {
		this.importo = importo;
	}

	public Set<ArFfLineafin> getArFfLineafins() {
		return this.arFfLineafins;
	}

	public void setArFfLineafins(Set<ArFfLineafin> arFfLineafins) {
		this.arFfLineafins = arFfLineafins;
	}

	public Boolean getAbilitato() {
		return abilitato;
	}

	public void setAbilitato(Boolean abilitato) {
		this.abilitato = abilitato;
	}

}
