package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArFfEroganteId generated by hbm2java
 */
@Embeddable
public class ArFfEroganteId implements java.io.Serializable {

	private long servizioTerriotorioId;
	private long organizzazioneId;

	public ArFfEroganteId() {
	}

	public ArFfEroganteId(long servizioTerriotorioId, long organizzazioneId) {
		this.servizioTerriotorioId = servizioTerriotorioId;
		this.organizzazioneId = organizzazioneId;
	}

	@Column(name = "SERVIZIO_TERRIOTORIO_ID", nullable = false, precision = 10, scale = 0)
	public long getServizioTerriotorioId() {
		return this.servizioTerriotorioId;
	}

	public void setServizioTerriotorioId(long servizioTerriotorioId) {
		this.servizioTerriotorioId = servizioTerriotorioId;
	}

	@Column(name = "ORGANIZZAZIONE_ID", nullable = false, precision = 10, scale = 0)
	public long getOrganizzazioneId() {
		return this.organizzazioneId;
	}

	public void setOrganizzazioneId(long organizzazioneId) {
		this.organizzazioneId = organizzazioneId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArFfEroganteId))
			return false;
		ArFfEroganteId castOther = (ArFfEroganteId) other;

		return (this.getServizioTerriotorioId() == castOther
				.getServizioTerriotorioId())
				&& (this.getOrganizzazioneId() == castOther
						.getOrganizzazioneId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getServizioTerriotorioId();
		result = 37 * result + (int) this.getOrganizzazioneId();
		return result;
	}

}
