package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArSpazio generated by hbm2java
 */
@Entity
@Table(name = "AR_SPAZIO")
public class ArSpazio implements java.io.Serializable {

	private long id;
	private String latitude;
	private String longitude;
	private Serializable shape;
	private String userIns;
	private Date dtIns;
	private String usrMod;
	private Date dtMod;
	private String belfiore;
	private String zonaIstat;
	private Set<ArDato> arDatos = new HashSet<ArDato>(0);

	public ArSpazio() {
	}

	public ArSpazio(long id, String userIns, Date dtIns, String belfiore) {
		this.id = id;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.belfiore = belfiore;
	}

	public ArSpazio(long id, String latitude, String longitude,
			Serializable shape, String userIns, Date dtIns, String usrMod,
			Date dtMod, String belfiore, String zonaIstat, Set<ArDato> arDatos) {
		this.id = id;
		this.latitude = latitude;
		this.longitude = longitude;
		this.shape = shape;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.usrMod = usrMod;
		this.dtMod = dtMod;
		this.belfiore = belfiore;
		this.zonaIstat = zonaIstat;
		this.arDatos = arDatos;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "LATITUDE", length = 50)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", length = 50)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "SHAPE")
	public Serializable getShape() {
		return this.shape;
	}

	public void setShape(Serializable shape) {
		this.shape = shape;
	}

	@Column(name = "USER_INS", nullable = false, length = 50)
	public String getUserIns() {
		return this.userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", nullable = false, length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "USR_MOD", length = 50)
	public String getUsrMod() {
		return this.usrMod;
	}

	public void setUsrMod(String usrMod) {
		this.usrMod = usrMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MOD", length = 7)
	public Date getDtMod() {
		return this.dtMod;
	}

	public void setDtMod(Date dtMod) {
		this.dtMod = dtMod;
	}

	@Column(name = "BELFIORE", nullable = false, length = 5)
	public String getBelfiore() {
		return this.belfiore;
	}

	public void setBelfiore(String belfiore) {
		this.belfiore = belfiore;
	}

	@Column(name = "ZONA_ISTAT", length = 20)
	public String getZonaIstat() {
		return this.zonaIstat;
	}

	public void setZonaIstat(String zonaIstat) {
		this.zonaIstat = zonaIstat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arSpazio")
	public Set<ArDato> getArDatos() {
		return this.arDatos;
	}

	public void setArDatos(Set<ArDato> arDatos) {
		this.arDatos = arDatos;
	}

}
