//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.10 at 04:16:35 PM CEST 
//


package it.webred.siso.ws.client.atlante.model.GetServiziOspite.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://sistematlante.it/AtlanteWebServices.ObjectModel.Messages}CodiceFonteEsterna" minOccurs="0"/>
 *         &lt;element ref="{http://sistematlante.it/AtlanteWebServices.ObjectModel.Messages}Matricola" minOccurs="0"/>
 *         &lt;element ref="{http://sistematlante.it/AtlanteWebServices.ObjectModel.Messages}DaData" minOccurs="0"/>
 *         &lt;element ref="{http://sistematlante.it/AtlanteWebServices.ObjectModel.Messages}CodiceFiscale" minOccurs="0"/>
 *         &lt;element ref="{http://sistematlante.it/AtlanteWebServices.ObjectModel.Messages}AData" minOccurs="0"/>
 *         &lt;element ref="{http://sistematlante.it/AtlanteWebServices.ObjectModel.Messages}Token" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codiceFonteEsterna",
    "matricola",
    "daData",
    "codiceFiscale",
    "aData",
    "token"
})
@XmlRootElement(name = "request", namespace="http://sistematlante.it/gestioneServizi")
public class Request {

    @XmlElement(name = "CodiceFonteEsterna", namespace = "http://schemas.datacontract.org/2004/07/AtlanteWebServices.ObjectModel.Messages.GestioneServizi")
    protected String codiceFonteEsterna;
    @XmlElement(name = "Matricola", namespace = "http://schemas.datacontract.org/2004/07/AtlanteWebServices.ObjectModel.Messages.GestioneServizi")
    protected String matricola;
    @XmlElement(name = "DaData", namespace = "http://schemas.datacontract.org/2004/07/AtlanteWebServices.ObjectModel.Messages.GestioneServizi")
    protected String daData;
    @XmlElement(name = "CodiceFiscale", namespace = "http://schemas.datacontract.org/2004/07/AtlanteWebServices.ObjectModel.Messages.GestioneServizi")
    protected String codiceFiscale;
    @XmlElement(name = "AData", namespace = "http://schemas.datacontract.org/2004/07/AtlanteWebServices.ObjectModel.Messages.GestioneServizi")
    protected String aData;
    @XmlElement(name = "Token", namespace = "http://schemas.datacontract.org/2004/07/AtlanteWebServices.ObjectModel.Messages.GestioneServizi")
    protected String token;

    /**
     * Gets the value of the codiceFonteEsterna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFonteEsterna() {
        return codiceFonteEsterna;
    }

    /**
     * Sets the value of the codiceFonteEsterna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFonteEsterna(String value) {
        this.codiceFonteEsterna = value;
    }

    /**
     * Gets the value of the matricola property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatricola() {
        return matricola;
    }

    /**
     * Sets the value of the matricola property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatricola(String value) {
        this.matricola = value;
    }

    /**
     * Gets the value of the daData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaData() {
        return daData;
    }

    /**
     * Sets the value of the daData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaData(String value) {
        this.daData = value;
    }

    /**
     * Gets the value of the codiceFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * Sets the value of the codiceFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscale(String value) {
        this.codiceFiscale = value;
    }

    /**
     * Gets the value of the aData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAData() {
        return aData;
    }

    /**
     * Sets the value of the aData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAData(String value) {
        this.aData = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

}
