//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.10 at 02:23:38 PM CEST 
//
@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://sistematlante.it/gestioneServizi", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.webred.siso.ws.client.atlante.model.GetServiziOspite.request;
