package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArCsTrasfFondi generated by hbm2java
 */
@Entity
@Table(name = "AR_CS_TRASF_FONDI")
public class ArCsTrasfFondi implements java.io.Serializable {

	private long id;
	private ArCsSoggettoCs arCsSoggettoCs;
	private ArCsDatoCs arCsDatoCs;
	private BigDecimal quotaEuro;
	private String userIns;
	private Date dtIns;
	private String usrMod;
	private Date dtMod;

	public ArCsTrasfFondi() {
	}

	public ArCsTrasfFondi(long id, ArCsSoggettoCs arCsSoggettoCs,
			ArCsDatoCs arCsDatoCs, BigDecimal quotaEuro, String userIns,
			Date dtIns) {
		this.id = id;
		this.arCsSoggettoCs = arCsSoggettoCs;
		this.arCsDatoCs = arCsDatoCs;
		this.quotaEuro = quotaEuro;
		this.userIns = userIns;
		this.dtIns = dtIns;
	}

	public ArCsTrasfFondi(long id, ArCsSoggettoCs arCsSoggettoCs,
			ArCsDatoCs arCsDatoCs, BigDecimal quotaEuro, String userIns,
			Date dtIns, String usrMod, Date dtMod) {
		this.id = id;
		this.arCsSoggettoCs = arCsSoggettoCs;
		this.arCsDatoCs = arCsDatoCs;
		this.quotaEuro = quotaEuro;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.usrMod = usrMod;
		this.dtMod = dtMod;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOGGETTO_CS_ID", nullable = false)
	public ArCsSoggettoCs getArCsSoggettoCs() {
		return this.arCsSoggettoCs;
	}

	public void setArCsSoggettoCs(ArCsSoggettoCs arCsSoggettoCs) {
		this.arCsSoggettoCs = arCsSoggettoCs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DATO_CS_ID", nullable = false)
	public ArCsDatoCs getArCsDatoCs() {
		return this.arCsDatoCs;
	}

	public void setArCsDatoCs(ArCsDatoCs arCsDatoCs) {
		this.arCsDatoCs = arCsDatoCs;
	}

	@Column(name = "QUOTA_EURO", nullable = false, precision = 8)
	public BigDecimal getQuotaEuro() {
		return this.quotaEuro;
	}

	public void setQuotaEuro(BigDecimal quotaEuro) {
		this.quotaEuro = quotaEuro;
	}

	@Column(name = "USER_INS", nullable = false, length = 50)
	public String getUserIns() {
		return this.userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", nullable = false, length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "USR_MOD", length = 50)
	public String getUsrMod() {
		return this.usrMod;
	}

	public void setUsrMod(String usrMod) {
		this.usrMod = usrMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MOD", length = 7)
	public Date getDtMod() {
		return this.dtMod;
	}

	public void setDtMod(Date dtMod) {
		this.dtMod = dtMod;
	}

}
