package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArFfProgetto generated by hbm2java
 */
@Entity
@Table(name = "AR_FF_PROGETTO")
public class ArFfProgetto implements java.io.Serializable {

	private long id;
	private String codiceMemo;
	private String descrizione;
	private String userIns;
	private Date dtIns;
	private String usrMod;
	private Date dtMod;
	private Character abilitato;
	private Set<ArFfLineafin> arFfLineafins = new HashSet<ArFfLineafin>(0);

	public ArFfProgetto() {
	}

	public ArFfProgetto(long id, String codiceMemo, String descrizione,
			String userIns, Date dtIns) {
		this.id = id;
		this.codiceMemo = codiceMemo;
		this.descrizione = descrizione;
		this.userIns = userIns;
		this.dtIns = dtIns;
	}

	public ArFfProgetto(long id, String codiceMemo, String descrizione,
			String userIns, Date dtIns, String usrMod, Date dtMod,
			Character abilitato, Set<ArFfLineafin> arFfLineafins) {
		this.id = id;
		this.codiceMemo = codiceMemo;
		this.descrizione = descrizione;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.usrMod = usrMod;
		this.dtMod = dtMod;
		this.abilitato = abilitato;
		this.arFfLineafins = arFfLineafins;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CODICE_MEMO", nullable = false, length = 20)
	public String getCodiceMemo() {
		return this.codiceMemo;
	}

	public void setCodiceMemo(String codiceMemo) {
		this.codiceMemo = codiceMemo;
	}

	@Column(name = "DESCRIZIONE", nullable = false)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "USER_INS", nullable = false, length = 50)
	public String getUserIns() {
		return this.userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", nullable = false, length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "USR_MOD", length = 50)
	public String getUsrMod() {
		return this.usrMod;
	}

	public void setUsrMod(String usrMod) {
		this.usrMod = usrMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MOD", length = 7)
	public Date getDtMod() {
		return this.dtMod;
	}

	public void setDtMod(Date dtMod) {
		this.dtMod = dtMod;
	}

	@Column(name = "ABILITATO", length = 1)
	public Character getAbilitato() {
		return this.abilitato;
	}

	public void setAbilitato(Character abilitato) {
		this.abilitato = abilitato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arFfProgetto")
	public Set<ArFfLineafin> getArFfLineafins() {
		return this.arFfLineafins;
	}

	public void setArFfLineafins(Set<ArFfLineafin> arFfLineafins) {
		this.arFfLineafins = arFfLineafins;
	}

}
