package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArPeriodo generated by hbm2java
 */
@Entity
@Table(name = "AR_PERIODO")
public class ArPeriodo implements java.io.Serializable {

	private long id;
	private String descrizione;
	private String aaaaDa;
	private String mmDa;
	private String ggDa;
	private String aaaaA;
	private String mmA;
	private String ggA;
	private String userIns;
	private Date dtIns;
	private String usrMod;
	private Date dtMod;
	private Set<ArDato> arDatos = new HashSet<ArDato>(0);

	public ArPeriodo() {
	}

	public ArPeriodo(long id, String descrizione, String aaaaDa, String mmDa,
			String ggDa, String aaaaA, String mmA, String ggA, String userIns,
			Date dtIns) {
		this.id = id;
		this.descrizione = descrizione;
		this.aaaaDa = aaaaDa;
		this.mmDa = mmDa;
		this.ggDa = ggDa;
		this.aaaaA = aaaaA;
		this.mmA = mmA;
		this.ggA = ggA;
		this.userIns = userIns;
		this.dtIns = dtIns;
	}

	public ArPeriodo(long id, String descrizione, String aaaaDa, String mmDa,
			String ggDa, String aaaaA, String mmA, String ggA, String userIns,
			Date dtIns, String usrMod, Date dtMod, Set<ArDato> arDatos) {
		this.id = id;
		this.descrizione = descrizione;
		this.aaaaDa = aaaaDa;
		this.mmDa = mmDa;
		this.ggDa = ggDa;
		this.aaaaA = aaaaA;
		this.mmA = mmA;
		this.ggA = ggA;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.usrMod = usrMod;
		this.dtMod = dtMod;
		this.arDatos = arDatos;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "DESCRIZIONE", nullable = false)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "AAAA_DA", nullable = false, length = 4)
	public String getAaaaDa() {
		return this.aaaaDa;
	}

	public void setAaaaDa(String aaaaDa) {
		this.aaaaDa = aaaaDa;
	}

	@Column(name = "MM_DA", nullable = false, length = 2)
	public String getMmDa() {
		return this.mmDa;
	}

	public void setMmDa(String mmDa) {
		this.mmDa = mmDa;
	}

	@Column(name = "GG_DA", nullable = false, length = 2)
	public String getGgDa() {
		return this.ggDa;
	}

	public void setGgDa(String ggDa) {
		this.ggDa = ggDa;
	}

	@Column(name = "AAAA_A", nullable = false, length = 4)
	public String getAaaaA() {
		return this.aaaaA;
	}

	public void setAaaaA(String aaaaA) {
		this.aaaaA = aaaaA;
	}

	@Column(name = "MM_A", nullable = false, length = 2)
	public String getMmA() {
		return this.mmA;
	}

	public void setMmA(String mmA) {
		this.mmA = mmA;
	}

	@Column(name = "GG_A", nullable = false, length = 2)
	public String getGgA() {
		return this.ggA;
	}

	public void setGgA(String ggA) {
		this.ggA = ggA;
	}

	@Column(name = "USER_INS", nullable = false, length = 50)
	public String getUserIns() {
		return this.userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", nullable = false, length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "USR_MOD", length = 50)
	public String getUsrMod() {
		return this.usrMod;
	}

	public void setUsrMod(String usrMod) {
		this.usrMod = usrMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MOD", length = 7)
	public Date getDtMod() {
		return this.dtMod;
	}

	public void setDtMod(Date dtMod) {
		this.dtMod = dtMod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arPeriodo")
	public Set<ArDato> getArDatos() {
		return this.arDatos;
	}

	public void setArDatos(Set<ArDato> arDatos) {
		this.arDatos = arDatos;
	}

}
