package it.umbriadigitale.argo.data.cs.data;

// Generated 26-ott-2015 13.12.17 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArQClasse generated by hbm2java
 */
@Entity
@Table(name = "AR_Q_CLASSE")
public class ArQClasse implements java.io.Serializable {

	private long id;
	private ArQModello arQModello;
	private ArTClasse arTClasse;
	private ArCsAreat arCsAreat;
	private ArQClasse arQClasse;
	private String userIns;
	private Date dtIns;
	private String usrMod;
	private Date dtMod;
	private String tooltip;
	private Character abilitato;
	private Set<ArFfServizioClasse> arFfServizioClasses = new HashSet<ArFfServizioClasse>(
			0);
	private Set<ArCsConsuntivoServ> arCsConsuntivoServs = new HashSet<ArCsConsuntivoServ>(
			0);
	private Set<ArQClasse> arQClasses = new HashSet<ArQClasse>(0);

	public ArQClasse() {
	}

	public ArQClasse(long id, ArTClasse arTClasse, ArCsAreat arCsAreat,
			String userIns, Date dtIns) {
		this.id = id;
		this.arTClasse = arTClasse;
		this.arCsAreat = arCsAreat;
		this.userIns = userIns;
		this.dtIns = dtIns;
	}

	public ArQClasse(long id, ArQModello arQModello, ArTClasse arTClasse,
			ArCsAreat arCsAreat, ArQClasse arQClasse, String userIns,
			Date dtIns, String usrMod, Date dtMod, String tooltip,
			Character abilitato, Set<ArFfServizioClasse> arFfServizioClasses,
			Set<ArCsConsuntivoServ> arCsConsuntivoServs,
			Set<ArQClasse> arQClasses) {
		this.id = id;
		this.arQModello = arQModello;
		this.arTClasse = arTClasse;
		this.arCsAreat = arCsAreat;
		this.arQClasse = arQClasse;
		this.userIns = userIns;
		this.dtIns = dtIns;
		this.usrMod = usrMod;
		this.dtMod = dtMod;
		this.tooltip = tooltip;
		this.abilitato = abilitato;
		this.arFfServizioClasses = arFfServizioClasses;
		this.arCsConsuntivoServs = arCsConsuntivoServs;
		this.arQClasses = arQClasses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODELLO_ID")
	public ArQModello getArQModello() {
		return this.arQModello;
	}

	public void setArQModello(ArQModello arQModello) {
		this.arQModello = arQModello;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "T_CLASSE_ID", nullable = false)
	public ArTClasse getArTClasse() {
		return this.arTClasse;
	}

	public void setArTClasse(ArTClasse arTClasse) {
		this.arTClasse = arTClasse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AREAT_ID", nullable = false)
	public ArCsAreat getArCsAreat() {
		return this.arCsAreat;
	}

	public void setArCsAreat(ArCsAreat arCsAreat) {
		this.arCsAreat = arCsAreat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Q_CLASSE_ID")
	public ArQClasse getArQClasse() {
		return this.arQClasse;
	}

	public void setArQClasse(ArQClasse arQClasse) {
		this.arQClasse = arQClasse;
	}

	@Column(name = "USER_INS", nullable = false, length = 50)
	public String getUserIns() {
		return this.userIns;
	}

	public void setUserIns(String userIns) {
		this.userIns = userIns;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_INS", nullable = false, length = 7)
	public Date getDtIns() {
		return this.dtIns;
	}

	public void setDtIns(Date dtIns) {
		this.dtIns = dtIns;
	}

	@Column(name = "USR_MOD", length = 50)
	public String getUsrMod() {
		return this.usrMod;
	}

	public void setUsrMod(String usrMod) {
		this.usrMod = usrMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_MOD", length = 7)
	public Date getDtMod() {
		return this.dtMod;
	}

	public void setDtMod(Date dtMod) {
		this.dtMod = dtMod;
	}

	@Column(name = "TOOLTIP", length = 4000)
	public String getTooltip() {
		return this.tooltip;
	}

	public void setTooltip(String tooltip) {
		this.tooltip = tooltip;
	}

	@Column(name = "ABILITATO", length = 1)
	public Character getAbilitato() {
		return this.abilitato;
	}

	public void setAbilitato(Character abilitato) {
		this.abilitato = abilitato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arQClasse")
	public Set<ArFfServizioClasse> getArFfServizioClasses() {
		return this.arFfServizioClasses;
	}

	public void setArFfServizioClasses(
			Set<ArFfServizioClasse> arFfServizioClasses) {
		this.arFfServizioClasses = arFfServizioClasses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arQClasse")
	public Set<ArCsConsuntivoServ> getArCsConsuntivoServs() {
		return this.arCsConsuntivoServs;
	}

	public void setArCsConsuntivoServs(
			Set<ArCsConsuntivoServ> arCsConsuntivoServs) {
		this.arCsConsuntivoServs = arCsConsuntivoServs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arQClasse")
	public Set<ArQClasse> getArQClasses() {
		return this.arQClasses;
	}

	public void setArQClasses(Set<ArQClasse> arQClasses) {
		this.arQClasses = arQClasses;
	}

}
