//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.21 at 01:17:40 PM CEST 
//


package com.osmosit.siso.flussoinps.psa_2016.binding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SINAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SINAType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="NecessitaInterventiSociali">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Mobilita" type="{http://inps.it/Casellario}MobilitaType" />
 *       &lt;attribute name="AttivitaVitaQuotidiana" type="{http://inps.it/Casellario}AttivitaVitaQuotidianaType" />
 *       &lt;attribute name="DisturbiAreaCognitiva" type="{http://inps.it/Casellario}DisturbiAreaCognitivaType" />
 *       &lt;attribute name="DisturbiComportamentali" type="{http://inps.it/Casellario}DisturbiComportamentaliType" />
 *       &lt;attribute name="NecessitaCureSanitarie" type="{http://inps.it/Casellario}NecessitaCureSanitarieType" />
 *       &lt;attribute name="AreaReddituale" type="{http://inps.it/Casellario}AreaRedditualeType" />
 *       &lt;attribute name="AreaSupporto" type="{http://inps.it/Casellario}AreaSupportoType" />
 *       &lt;attribute name="FonteDerivazioneValutazione" type="{http://inps.it/Casellario}FonteDerivazioneValutazioneType" />
 *       &lt;attribute name="StrumentoValutazione" type="{http://inps.it/Casellario}StrumentoValutazioneType" />
 *       &lt;attribute name="InvCiv" type="{http://inps.it/Casellario}InvCivType" />
 *       &lt;attribute name="FonteDerivazioneInvalidita" type="{http://inps.it/Casellario}FonteDerivazioneInvaliditaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SINAType", propOrder = {
    "necessitaInterventiSociali"
})
public class SINA {

    @XmlElement(name = "NecessitaInterventiSociali", required = true)
    protected List<String> necessitaInterventiSociali;
    @XmlAttribute(name = "Mobilita")
    protected String mobilita;
    @XmlAttribute(name = "AttivitaVitaQuotidiana")
    protected String attivitaVitaQuotidiana;
    @XmlAttribute(name = "DisturbiAreaCognitiva")
    protected String disturbiAreaCognitiva;
    @XmlAttribute(name = "DisturbiComportamentali")
    protected String disturbiComportamentali;
    @XmlAttribute(name = "NecessitaCureSanitarie")
    protected String necessitaCureSanitarie;
    @XmlAttribute(name = "AreaReddituale")
    protected String areaReddituale;
    @XmlAttribute(name = "AreaSupporto")
    protected String areaSupporto;
    @XmlAttribute(name = "FonteDerivazioneValutazione")
    protected String fonteDerivazioneValutazione;
    @XmlAttribute(name = "StrumentoValutazione")
    protected String strumentoValutazione;
    @XmlAttribute(name = "InvCiv")
    protected String invCiv;
    @XmlAttribute(name = "FonteDerivazioneInvalidita")
    protected String fonteDerivazioneInvalidita;

    /**
     * Gets the value of the necessitaInterventiSociali property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the necessitaInterventiSociali property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNecessitaInterventiSociali().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNecessitaInterventiSociali() {
        if (necessitaInterventiSociali == null) {
            necessitaInterventiSociali = new ArrayList<String>();
        }
        return this.necessitaInterventiSociali;
    }

    /**
     * Gets the value of the mobilita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilita() {
        return mobilita;
    }

    /**
     * Sets the value of the mobilita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilita(String value) {
        this.mobilita = value;
    }

    /**
     * Gets the value of the attivitaVitaQuotidiana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttivitaVitaQuotidiana() {
        return attivitaVitaQuotidiana;
    }

    /**
     * Sets the value of the attivitaVitaQuotidiana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttivitaVitaQuotidiana(String value) {
        this.attivitaVitaQuotidiana = value;
    }

    /**
     * Gets the value of the disturbiAreaCognitiva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisturbiAreaCognitiva() {
        return disturbiAreaCognitiva;
    }

    /**
     * Sets the value of the disturbiAreaCognitiva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisturbiAreaCognitiva(String value) {
        this.disturbiAreaCognitiva = value;
    }

    /**
     * Gets the value of the disturbiComportamentali property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisturbiComportamentali() {
        return disturbiComportamentali;
    }

    /**
     * Sets the value of the disturbiComportamentali property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisturbiComportamentali(String value) {
        this.disturbiComportamentali = value;
    }

    /**
     * Gets the value of the necessitaCureSanitarie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNecessitaCureSanitarie() {
        return necessitaCureSanitarie;
    }

    /**
     * Sets the value of the necessitaCureSanitarie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNecessitaCureSanitarie(String value) {
        this.necessitaCureSanitarie = value;
    }

    /**
     * Gets the value of the areaReddituale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaReddituale() {
        return areaReddituale;
    }

    /**
     * Sets the value of the areaReddituale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaReddituale(String value) {
        this.areaReddituale = value;
    }

    /**
     * Gets the value of the areaSupporto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaSupporto() {
        return areaSupporto;
    }

    /**
     * Sets the value of the areaSupporto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaSupporto(String value) {
        this.areaSupporto = value;
    }

    /**
     * Gets the value of the fonteDerivazioneValutazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFonteDerivazioneValutazione() {
        return fonteDerivazioneValutazione;
    }

    /**
     * Sets the value of the fonteDerivazioneValutazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFonteDerivazioneValutazione(String value) {
        this.fonteDerivazioneValutazione = value;
    }

    /**
     * Gets the value of the strumentoValutazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrumentoValutazione() {
        return strumentoValutazione;
    }

    /**
     * Sets the value of the strumentoValutazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrumentoValutazione(String value) {
        this.strumentoValutazione = value;
    }

    /**
     * Gets the value of the invCiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvCiv() {
        return invCiv;
    }

    /**
     * Sets the value of the invCiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvCiv(String value) {
        this.invCiv = value;
    }

    /**
     * Gets the value of the fonteDerivazioneInvalidita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFonteDerivazioneInvalidita() {
        return fonteDerivazioneInvalidita;
    }

    /**
     * Sets the value of the fonteDerivazioneInvalidita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFonteDerivazioneInvalidita(String value) {
        this.fonteDerivazioneInvalidita = value;
    }

}
