
  CREATE TABLE "ARGO_RM"."AR_RP_ANAGRAFICA" 
   (	"ID" NUMBER, 
	"COGNOME" VARCHAR2(100) NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"CF" CHAR(16), 
	"GENERE" CHAR(1), 
	"DATA_NASCITA" DATE, 
	"CITTADINANZA" VARCHAR2(100), 
	"ID_STRUTTURA" NUMBER, 
	"ID_AREA_STRUTTURA" NUMBER, 
	"UNITA_ABITATIVA" VARCHAR2(100), 
	"FLG_REFERENTE" NUMBER, 
	"ID_REFERENTE" NUMBER, 
	"ID_TITOLO_STUDIO" NUMBER, 
	"STATO_TIT_CONSEGUITO_COD" VARCHAR2(100), 
	"STATO_TIT_CONSEGUITO_DES" VARCHAR2(100), 
	"ID_CONDIZIONE_LAVORATIVA" NUMBER, 
	"ID_ORDINE_SCUOLA" NUMBER, 
	"ID_VULNERABILITA" NUMBER, 
	"NOTE" VARCHAR2(100), 
	"DT_INS" DATE, 
	"USR_INS" VARCHAR2(50), 
	"DT_MOD" DATE, 
	"USR_MOD" VARCHAR2(50), 
	"COMUNE_NASCITA_COD" VARCHAR2(100), 
	"COMUNE_NASCITA_DES" VARCHAR2(100), 
	"PROV_NASCITA_COD" VARCHAR2(4), 
	"STATO_NASCITA_COD" VARCHAR2(30), 
	"STATO_NASCITA_DES" VARCHAR2(255), 
	"COMUNE_RESIDENZA_COD" VARCHAR2(30), 
	"COMUNE_RESIDENZA_DES" VARCHAR2(100), 
	"PROV_RESIDENZA_COD" VARCHAR2(4), 
	"ID_PARENTELA" NUMBER, 
	"COMUNE_DOMICILIO_COD" VARCHAR2(30), 
	"COMUNE_DOMICILIO_DES" VARCHAR2(100), 
	"PROV_DOMICILIO_COD" VARCHAR2(4), 
	"ID_MUNICIPIO_RES" NUMBER, 
	"ID_MUNICIPIO_DOM" NUMBER, 
	"DATA_INSEDIAMENTO" DATE NOT NULL ENABLE, 
	"DATA_USCITA" DATE, 
	"INDIRIZZO_RESIDENZA" VARCHAR2(100), 
	"INDIRIZZO_DOMICILIO" VARCHAR2(100), 
	 CONSTRAINT "AR_RP_ANAGRAFICA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CT_F704_GIT"  ENABLE, 
	 CONSTRAINT "FK_AR_RP_STRUTTURA1" FOREIGN KEY ("ID_STRUTTURA")
	  REFERENCES "ARGO_RM"."AR_RP_STRUTTURA" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CT_F704_GIT" ;