ALTER TABLE CS_D_DOC_INDIVIDUALE ADD DIPARTIMENTO_PROTOCOLLO VARCHAR2(2);
ALTER TABLE CS_D_DOC_INDIVIDUALE ADD NUMERO_PROTOCOLLO VARCHAR2(6);
ALTER TABLE CS_D_DOC_INDIVIDUALE ADD ANNO_PROTOCOLLO VARCHAR2(4);
ALTER TABLE CS_D_DOC_INDIVIDUALE ADD DATI_PROTOCOLLO_CLOB CLOB;
