ALTER TABLE CS_TB_SOTTOCARTELLA_DOC ADD PROTOCOLLO NUMBER(22,0) DEFAULT 0;
ALTER TABLE CS_TB_SOTTOCARTELLA_DOC ADD PROTOCOLLO_DA_SIGESS NUMBER(22,0) DEFAULT 0;
ALTER TABLE CS_TB_SOTTOCARTELLA_DOC ADD CODICE VARCHAR2(50);