package it.webred.siso.esb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-06-22T13:33:46.214+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://esb.siso.webred.it", name = "MedicoServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MedicoServicePortType {

    @WebResult(name = "getMedicoReturn", targetNamespace = "http://esb.siso.webred.it", partName = "getMedicoReturn")
    @Action(input = "getMedico", output = "//esb.siso.webred.it/MediciRegione/getMedicoResponse")
    @WebMethod(action = "getMedico")
    public Medico getMedico(
        @WebParam(partName = "codiceRegionale", name = "codiceRegionale", targetNamespace = "http://esb.siso.webred.it")
        java.lang.String codiceRegionale
    );
}
