//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 08:57:40 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.inps.it/schema/PSA/PSA_InvioPrestazioni_Input.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.osmosit.siso.flussoinps.psa_invioprestazioni;
