//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 08:57:40 AM CEST 
//


package com.osmosit.siso.flussoinps.psa_invioprestazioni;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PrestazioniBeneficiario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrestazioniBeneficiario">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Carattere" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumeroProtocolloDSU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AnnoProtocollo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataDSU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Codice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Denominazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProtocolloEnte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataEvento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataInizio" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DataFine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataErogazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Importo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PeriodoErogazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ImportoMensile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QuotaEnte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QuotaUtente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QuotaSSN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QuotaRichiesta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SogliaISEE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrestazioniBeneficiario", propOrder = {
    "carattere",
    "numeroProtocolloDSU",
    "annoProtocollo",
    "dataDSU",
    "codice",
    "denominazione",
    "protocolloEnte",
    "dataEvento",
    "dataInizio",
    "dataFine",
    "dataErogazione",
    "importo",
    "periodoErogazione",
    "importoMensile",
    "quotaEnte",
    "quotaUtente",
    "quotaSSN",
    "quotaRichiesta",
    "sogliaISEE"
})
public class PrestazioniBeneficiario {

    @XmlElement(name = "Carattere")
    protected String carattere;
    @XmlElement(name = "NumeroProtocolloDSU")
    protected String numeroProtocolloDSU;
    @XmlElement(name = "AnnoProtocollo")
    protected String annoProtocollo;
    @XmlElement(name = "DataDSU")
    protected String dataDSU;
    @XmlElement(name = "Codice")
    protected String codice;
    @XmlElement(name = "Denominazione")
    protected String denominazione;
    @XmlElement(name = "ProtocolloEnte")
    protected String protocolloEnte;
    @XmlElement(name = "DataEvento")
    protected String dataEvento;
    @XmlElement(name = "DataInizio") 
    protected String dataInizio;
    @XmlElement(name = "DataFine")
    protected String dataFine;
    @XmlElement(name = "DataErogazione")
    protected String dataErogazione;
    @XmlElement(name = "Importo")
    protected String importo;
    @XmlElement(name = "PeriodoErogazione")
    protected String periodoErogazione;
    @XmlElement(name = "ImportoMensile")
    protected String importoMensile;
    @XmlElement(name = "QuotaEnte")
    protected String quotaEnte;
    @XmlElement(name = "QuotaUtente")
    protected String quotaUtente;
    @XmlElement(name = "QuotaSSN")
    protected String quotaSSN;
    @XmlElement(name = "QuotaRichiesta")
    protected String quotaRichiesta;
    @XmlElement(name = "SogliaISEE")
    protected String sogliaISEE;

    /**
     * Gets the value of the carattere property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarattere() {
        return carattere;
    }

    /**
     * Sets the value of the carattere property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarattere(String value) {
        this.carattere = value;
    }

    /**
     * Gets the value of the numeroProtocolloDSU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroProtocolloDSU() {
        return numeroProtocolloDSU;
    }

    /**
     * Sets the value of the numeroProtocolloDSU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroProtocolloDSU(String value) {
        this.numeroProtocolloDSU = value;
    }

    /**
     * Gets the value of the annoProtocollo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnoProtocollo() {
        return annoProtocollo;
    }

    /**
     * Sets the value of the annoProtocollo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnoProtocollo(String value) {
        this.annoProtocollo = value;
    }

    /**
     * Gets the value of the dataDSU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataDSU() {
        return dataDSU;
    }

    /**
     * Sets the value of the dataDSU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataDSU(String value) {
        this.dataDSU = value;
    }

    /**
     * Gets the value of the codice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodice() {
        return codice;
    }

    /**
     * Sets the value of the codice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodice(String value) {
        this.codice = value;
    }

    /**
     * Gets the value of the denominazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazione() {
        return denominazione;
    }

    /**
     * Sets the value of the denominazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazione(String value) {
        this.denominazione = value;
    }

    /**
     * Gets the value of the protocolloEnte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolloEnte() {
        return protocolloEnte;
    }

    /**
     * Sets the value of the protocolloEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolloEnte(String value) {
        this.protocolloEnte = value;
    }

    /**
     * Gets the value of the dataEvento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataEvento() {
        return dataEvento;
    }

    /**
     * Sets the value of the dataEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataEvento(String value) {
        this.dataEvento = value;
    }

    /**
     * Gets the value of the dataInizio property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDataInizio() {
        return dataInizio;
    }

    /**
     * Sets the value of the dataInizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataInizio(String value) {
        this.dataInizio = value;
    }

    /**
     * Gets the value of the dataFine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFine() {
        return dataFine;
    }

    /**
     * Sets the value of the dataFine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFine(String value) {
        this.dataFine = value;
    }

    /**
     * Gets the value of the dataErogazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataErogazione() {
        return dataErogazione;
    }

    /**
     * Sets the value of the dataErogazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataErogazione(String value) {
        this.dataErogazione = value;
    }

    /**
     * Gets the value of the importo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporto() {
        return importo;
    }

    /**
     * Sets the value of the importo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporto(String value) {
        this.importo = value;
    }

    /**
     * Gets the value of the periodoErogazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodoErogazione() {
        return periodoErogazione;
    }

    /**
     * Sets the value of the periodoErogazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodoErogazione(String value) {
        this.periodoErogazione = value;
    }

    /**
     * Gets the value of the importoMensile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportoMensile() {
        return importoMensile;
    }

    /**
     * Sets the value of the importoMensile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportoMensile(String value) {
        this.importoMensile = value;
    }

    /**
     * Gets the value of the quotaEnte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotaEnte() {
        return quotaEnte;
    }

    /**
     * Sets the value of the quotaEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotaEnte(String value) {
        this.quotaEnte = value;
    }

    /**
     * Gets the value of the quotaUtente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotaUtente() {
        return quotaUtente;
    }

    /**
     * Sets the value of the quotaUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotaUtente(String value) {
        this.quotaUtente = value;
    }

    /**
     * Gets the value of the quotaSSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotaSSN() {
        return quotaSSN;
    }

    /**
     * Sets the value of the quotaSSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotaSSN(String value) {
        this.quotaSSN = value;
    }

    /**
     * Gets the value of the quotaRichiesta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotaRichiesta() {
        return quotaRichiesta;
    }

    /**
     * Sets the value of the quotaRichiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotaRichiesta(String value) {
        this.quotaRichiesta = value;
    }

    /**
     * Gets the value of the sogliaISEE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSogliaISEE() {
        return sogliaISEE;
    }

    /**
     * Sets the value of the sogliaISEE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSogliaISEE(String value) {
        this.sogliaISEE = value;
    }

}
