//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 08:57:40 AM CEST 
//


package com.osmosit.siso.flussoinps.psa_invioprestazioni;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnagraficaBeneficiario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnagraficaBeneficiario">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cognome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Nome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AnnoNascita" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LuogoNascita" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Sesso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CittadinanzaISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecondaCittadinanzaISO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnagraficaBeneficiario", propOrder = {
    "cognome",
    "nome",
    "annoNascita",
    "luogoNascita",
    "sesso",
    "cittadinanzaISO",
    "secondaCittadinanzaISO"
})
public class AnagraficaBeneficiario {

    @XmlElement(name = "Cognome")
    protected String cognome;
    @XmlElement(name = "Nome")
    protected String nome;
    @XmlElement(name = "AnnoNascita")
    protected String annoNascita;
    @XmlElement(name = "LuogoNascita")
    protected String luogoNascita;
    @XmlElement(name = "Sesso")
    protected String sesso;
    @XmlElement(name = "CittadinanzaISO")
    protected String cittadinanzaISO;
    @XmlElement(name = "SecondaCittadinanzaISO")
    protected String secondaCittadinanzaISO;

    /**
     * Gets the value of the cognome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * Sets the value of the cognome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognome(String value) {
        this.cognome = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the annoNascita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnoNascita() {
        return annoNascita;
    }

    /**
     * Sets the value of the annoNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnoNascita(String value) {
        this.annoNascita = value;
    }

    /**
     * Gets the value of the luogoNascita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLuogoNascita() {
        return luogoNascita;
    }

    /**
     * Sets the value of the luogoNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLuogoNascita(String value) {
        this.luogoNascita = value;
    }

    /**
     * Gets the value of the sesso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSesso() {
        return sesso;
    }

    /**
     * Sets the value of the sesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSesso(String value) {
        this.sesso = value;
    }

    /**
     * Gets the value of the cittadinanzaISO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCittadinanzaISO() {
        return cittadinanzaISO;
    }

    /**
     * Sets the value of the cittadinanzaISO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCittadinanzaISO(String value) {
        this.cittadinanzaISO = value;
    }

    /**
     * Gets the value of the secondaCittadinanzaISO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaCittadinanzaISO() {
        return secondaCittadinanzaISO;
    }

    /**
     * Sets the value of the secondaCittadinanzaISO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaCittadinanzaISO(String value) {
        this.secondaCittadinanzaISO = value;
    }

}
