//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 08:57:40 AM CEST 
//


package com.osmosit.siso.flussoinps.psa_invioprestazioni;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Beneficiario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Beneficiario">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodiceFiscale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Anagrafica" type="{http://ws.inps.it/schema/PSA/PSA_InvioPrestazioni_Input.xsd}AnagraficaBeneficiario"/>
 *         &lt;element name="Residenza" type="{http://ws.inps.it/schema/PSA/PSA_InvioPrestazioni_Input.xsd}ResidenzaBeneficiario" minOccurs="0"/>
 *         &lt;element name="Prestazione" type="{http://ws.inps.it/schema/PSA/PSA_InvioPrestazioni_Input.xsd}PrestazioniBeneficiario" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Beneficiario", propOrder = {
    "codiceFiscale",
    "anagrafica",
    "residenza",
    "prestazione"
})
public class Beneficiario {

    @XmlElement(name = "CodiceFiscale")
    protected String codiceFiscale;
    @XmlElement(name = "Anagrafica", required = true)
    protected AnagraficaBeneficiario anagrafica;
    @XmlElement(name = "Residenza")
    protected ResidenzaBeneficiario residenza;
    @XmlElement(name = "Prestazione", required = true)
    protected List<PrestazioniBeneficiario> prestazione;

    /**
     * Gets the value of the codiceFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * Sets the value of the codiceFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscale(String value) {
        this.codiceFiscale = value;
    }

    /**
     * Gets the value of the anagrafica property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaBeneficiario }
     *     
     */
    public AnagraficaBeneficiario getAnagrafica() {
        return anagrafica;
    }

    /**
     * Sets the value of the anagrafica property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaBeneficiario }
     *     
     */
    public void setAnagrafica(AnagraficaBeneficiario value) {
        this.anagrafica = value;
    }

    /**
     * Gets the value of the residenza property.
     * 
     * @return
     *     possible object is
     *     {@link ResidenzaBeneficiario }
     *     
     */
    public ResidenzaBeneficiario getResidenza() {
        return residenza;
    }

    /**
     * Sets the value of the residenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResidenzaBeneficiario }
     *     
     */
    public void setResidenza(ResidenzaBeneficiario value) {
        this.residenza = value;
    }

    /**
     * Gets the value of the prestazione property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prestazione property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrestazione().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrestazioniBeneficiario }
     * 
     * 
     */
    public List<PrestazioniBeneficiario> getPrestazione() {
        if (prestazione == null) {
            prestazione = new ArrayList<PrestazioniBeneficiario>();
        }
        return this.prestazione;
    }

}
