//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 08:57:40 AM CEST 
//


package com.osmosit.siso.flussoinps.psa_invioprestazioni;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.osmosit.siso.flussoinps.psa_invioprestazioni package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Inps_QNAME = new QName("http://ws.inps.it/schema/PSA/PSA_InvioPrestazioni_Input.xsd", "inps");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.osmosit.siso.flussoinps.psa_invioprestazioni
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PSAInvioPrestazioniInput }
     * 
     */
    public PSAInvioPrestazioniInput createPSAInvioPrestazioniInput() {
        return new PSAInvioPrestazioniInput();
    }

    /**
     * Create an instance of {@link Beneficiari }
     * 
     */
    public Beneficiari createBeneficiari() {
        return new Beneficiari();
    }

    /**
     * Create an instance of {@link Ente }
     * 
     */
    public Ente createEnte() {
        return new Ente();
    }

    /**
     * Create an instance of {@link Beneficiario }
     * 
     */
    public Beneficiario createBeneficiario() {
        return new Beneficiario();
    }

    /**
     * Create an instance of {@link ResidenzaBeneficiario }
     * 
     */
    public ResidenzaBeneficiario createResidenzaBeneficiario() {
        return new ResidenzaBeneficiario();
    }

    /**
     * Create an instance of {@link AnagraficaBeneficiario }
     * 
     */
    public AnagraficaBeneficiario createAnagraficaBeneficiario() {
        return new AnagraficaBeneficiario();
    }

    /**
     * Create an instance of {@link PrestazioniBeneficiario }
     * 
     */
    public PrestazioniBeneficiario createPrestazioniBeneficiario() {
        return new PrestazioniBeneficiario();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PSAInvioPrestazioniInput }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.inps.it/schema/PSA/PSA_InvioPrestazioni_Input.xsd", name = "inps")
    public JAXBElement<PSAInvioPrestazioniInput> createInps(PSAInvioPrestazioniInput value) {
        return new JAXBElement<PSAInvioPrestazioniInput>(_Inps_QNAME, PSAInvioPrestazioniInput.class, null, value);
    }

}
