//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 08:57:40 AM CEST 
//


package com.osmosit.siso.flussoinps.psa_invioprestazioni;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PSAInvioPrestazioniInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PSAInvioPrestazioniInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificazioneFlusso" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IdentificazioneEnte" type="{http://ws.inps.it/schema/PSA/PSA_InvioPrestazioni_Input.xsd}Ente"/>
 *         &lt;element name="Beneficiari" type="{http://ws.inps.it/schema/PSA/PSA_InvioPrestazioni_Input.xsd}Beneficiari"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PSAInvioPrestazioniInput", propOrder = {
    "identificazioneFlusso",
    "identificazioneEnte",
    "beneficiari"
})
public class PSAInvioPrestazioniInput {

    @XmlElement(name = "IdentificazioneFlusso", required = true)
    protected String identificazioneFlusso;
    @XmlElement(name = "IdentificazioneEnte", required = true)
    protected Ente identificazioneEnte;
    @XmlElement(name = "Beneficiari", required = true)
    protected Beneficiari beneficiari;

    /**
     * Gets the value of the identificazioneFlusso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificazioneFlusso() {
        return identificazioneFlusso;
    }

    /**
     * Sets the value of the identificazioneFlusso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificazioneFlusso(String value) {
        this.identificazioneFlusso = value;
    }

    /**
     * Gets the value of the identificazioneEnte property.
     * 
     * @return
     *     possible object is
     *     {@link Ente }
     *     
     */
    public Ente getIdentificazioneEnte() {
        return identificazioneEnte;
    }

    /**
     * Sets the value of the identificazioneEnte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ente }
     *     
     */
    public void setIdentificazioneEnte(Ente value) {
        this.identificazioneEnte = value;
    }

    /**
     * Gets the value of the beneficiari property.
     * 
     * @return
     *     possible object is
     *     {@link Beneficiari }
     *     
     */
    public Beneficiari getBeneficiari() {
        return beneficiari;
    }

    /**
     * Sets the value of the beneficiari property.
     * 
     * @param value
     *     allowed object is
     *     {@link Beneficiari }
     *     
     */
    public void setBeneficiari(Beneficiari value) {
        this.beneficiari = value;
    }

}
