package it.webred.cs.csa.ejb.dto.pai.sal;

public enum PaiSALDominiEnum {
	TIPO_SOGGETTO,
	INVIANTE,
	TIPO_ESPERIENZA,
	ESITO,
	LEGGE_104,
	LEGGE_68,
	ISCRIZIONE_CPI,
	RICHIEDENTE_ASILO,
	PRESA_CARICO_INV,
	PROPOSTA_FAM,
	PRESENZA_TUTOR,
	VICINANZA_ABIT,
	PERIODO_PROVA;
}
