package it.webred.siso.ws.client.esb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-06-09T13:44:14.546+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://esb.siso.webred.it", name = "SISOServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SISOServicePortType {

    @WebResult(name = "return", targetNamespace = "http://esb.siso.webred.it")
    @Action(input = "urn:doService", output = "urn:doServiceResponse")
    @RequestWrapper(localName = "doService", targetNamespace = "http://esb.siso.webred.it", className = "it.webred.siso.esb.DoService")
    @WebMethod(action = "urn:doService")
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://esb.siso.webred.it", className = "it.webred.siso.esb.DoServiceResponse")
    public java.lang.String doService(
        @WebParam(name = "payload", targetNamespace = "http://esb.siso.webred.it")
        java.lang.String payload,
        @WebParam(name = "serviceId", targetNamespace = "http://esb.siso.webred.it")
        java.lang.String serviceId
    );
}
