package it.webred.cs.csa.ejb.dto.pai.affido;

public enum PaiAffidoDominiEnum {

	NATURA_ACCOGLIENZA,
	TIPO_ACCOGLIENZA,
	SITUAZIONI_PARTICOLARI,
	COLLOCAMENTO,
	ENTITA_AFFIDO,
	IDONEITA_AFFIDATARI,
	BANCA_DATI_FAMIGLIE,
	FREQUENZA_CONTATTI,
	ESITO_AFFIDO,
	AFFIDATARI,
	CONVIVENZA_ORIG_AFF,
	RUOLO_SOGGETTO,
	TIPO_AFFIDO,
	ADOTTABILE,
	FAM_ORIG_INTERVENTI
	
}
