CREATE OR REPLACE VIEW CS_DEV2_RM.V_STRUTTURA_AREA
(ID_STRUTTURA,NOME_STRUTTURA,INDIRIZZO,TIPO_STRUTTURA,ABILITATO,ID_AREA,DESCRIZIONE)
AS
SELECT a.id AS id_struttura, a.NOME_STRUTTURA, a.INDIRIZZO,a.TIPO_STRUTTURA,a.ABILITATO,
c.id AS id_Area, c.DESCRIZIONE
FROM ARGO_RM.AR_RP_STRUTTURA a, ARGO_RM.AR_RP_REL_STRUTTURA_AREA b,  ARGO_RM.AR_RP_AREA c
WHERE a.ID=b.ID_STRUTTURA
AND b.ID_AREA=c.ID