package it.webred.cs.csa.ejb.dto.pai.affido;

public enum PaiAffidoDominiEnum {

	NATURA_ACCOGLIENZA,
	TIPO_ACCOGLIENZA,
	COLLOCAMENTO,
	ENTITA_AFFIDO,
	IDONEITA_AFFIDATARI,
	BANCA_DATI_FAMIGLIE,
	FREQUENZA_CONTATTI,
	AFFIDATARI,
	CONVIVENZA_ORIG_AFF,
	RUOLO_SOGGETTO,
	TIPO_AFFIDO,
	ADOTTABILE,
	FAM_ORIG_INTERVENTI,
	AUTORITA_PROVVEDIMENTO,
	CARATTERE_INSERIMENTO_RESIDENZIALE,
	FORME_AFFIDAMENTO_CONSOLIDATE,
	FORME_AFFIDAMENTO_ALTRE
	
}
