//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.24 at 04:01:25 PM CEST 
//


package org.hl7.v3.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityNameUseR2.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntityNameUseR2">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="Assumed"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="NameRepresentationUse"/>
 *     &lt;enumeration value="OLD"/>
 *     &lt;enumeration value="OR"/>
 *     &lt;enumeration value="PHON"/>
 *     &lt;enumeration value="SRCH"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="ANON"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="ABC"/>
 *     &lt;enumeration value="IDE"/>
 *     &lt;enumeration value="SYL"/>
 *     &lt;enumeration value="DN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EntityNameUseR2")
@XmlEnum
public enum EntityNameUseR2 {

    @XmlEnumValue("Assumed")
    ASSUMED("Assumed"),
    M("M"),
    N("N"),
    @XmlEnumValue("NameRepresentationUse")
    NAME_REPRESENTATION_USE("NameRepresentationUse"),
    OLD("OLD"),
    OR("OR"),
    PHON("PHON"),
    SRCH("SRCH"),
    T("T"),
    A("A"),
    ANON("ANON"),
    I("I"),
    P("P"),
    R("R"),
    ABC("ABC"),
    IDE("IDE"),
    SYL("SYL"),
    DN("DN");
    private final String value;

    EntityNameUseR2(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EntityNameUseR2 fromValue(String v) {
        for (EntityNameUseR2 c: EntityNameUseR2 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
