//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.24 at 04:01:25 PM CEST 
//


package org.hl7.v3.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRSS_MT999002ZZ.ObservationGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRSS_MT999002ZZ.ObservationGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II" minOccurs="0"/>
 *         &lt;element name="code" type="{urn:hl7-org:v3}CD"/>
 *         &lt;element name="statusCode" type="{urn:hl7-org:v3}CS"/>
 *         &lt;element name="effectiveTime" type="{urn:hl7-org:v3}IVL_TS" minOccurs="0"/>
 *         &lt;element name="confidentialityCode" type="{urn:hl7-org:v3}CV" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="subject" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.Subject1" minOccurs="0"/>
 *         &lt;element name="responsibleParty" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.ResponsibleParty" minOccurs="0"/>
 *         &lt;element name="performer" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.Performer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="author" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.Author1" minOccurs="0"/>
 *         &lt;element name="informant" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.Informant" minOccurs="0"/>
 *         &lt;element name="custodian" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.Custodian2" minOccurs="0"/>
 *         &lt;element name="inFulfillmentOf" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.InFulfillmentOf" minOccurs="0"/>
 *         &lt;element name="reference" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="predecessor" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.Predecessor1" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="component" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.Component4" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="successor" type="{urn:hl7-org:v3}PRSS_MT999002ZZ.Predecessor2" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="classCode" type="{urn:hl7-org:v3}ActClass" fixed="ACT" />
 *       &lt;attribute name="moodCode" type="{urn:hl7-org:v3}ActMood" fixed="EVN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRSS_MT999002ZZ.ObservationGroup", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "id",
    "code",
    "statusCode",
    "effectiveTime",
    "confidentialityCode",
    "subject",
    "responsibleParty",
    "performer",
    "author",
    "informant",
    "custodian",
    "inFulfillmentOf",
    "reference",
    "predecessor",
    "component",
    "successor"
})
public class PRSSMT999002ZZObservationGroup {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    protected II id;
    @XmlElement(required = true)
    protected CD code;
    @XmlElement(required = true)
    protected CS statusCode;
    protected IVLTS effectiveTime;
    protected List<CV> confidentialityCode;
    @XmlElementRef(name = "subject", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999002ZZSubject1> subject;
    @XmlElementRef(name = "responsibleParty", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999002ZZResponsibleParty> responsibleParty;
    @XmlElement(nillable = true)
    protected List<PRSSMT999002ZZPerformer> performer;
    @XmlElementRef(name = "author", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999002ZZAuthor1> author;
    @XmlElementRef(name = "informant", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999002ZZInformant> informant;
    @XmlElementRef(name = "custodian", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999002ZZCustodian2> custodian;
    @XmlElementRef(name = "inFulfillmentOf", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999002ZZInFulfillmentOf> inFulfillmentOf;
    @XmlElement(nillable = true)
    protected List<PRSSMT999002ZZReference> reference;
    @XmlElement(nillable = true)
    protected List<PRSSMT999002ZZPredecessor1> predecessor;
    @XmlElement(nillable = true)
    protected List<PRSSMT999002ZZComponent4> component;
    @XmlElementRef(name = "successor", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999002ZZPredecessor2> successor;
    @XmlAttribute(name = "classCode")
    protected ActClass classCode;
    @XmlAttribute(name = "moodCode")
    protected ActMood moodCode;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setId(II value) {
        this.id = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCode(CD value) {
        this.code = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setStatusCode(CS value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the effectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * Sets the value of the effectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setEffectiveTime(IVLTS value) {
        this.effectiveTime = value;
    }

    /**
     * Gets the value of the confidentialityCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the confidentialityCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfidentialityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CV }
     * 
     * 
     */
    public List<CV> getConfidentialityCode() {
        if (confidentialityCode == null) {
            confidentialityCode = new ArrayList<CV>();
        }
        return this.confidentialityCode;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZSubject1 }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999002ZZSubject1> getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZSubject1 }{@code >}
     *     
     */
    public void setSubject(JAXBElement<PRSSMT999002ZZSubject1> value) {
        this.subject = value;
    }

    /**
     * Gets the value of the responsibleParty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZResponsibleParty }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999002ZZResponsibleParty> getResponsibleParty() {
        return responsibleParty;
    }

    /**
     * Sets the value of the responsibleParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZResponsibleParty }{@code >}
     *     
     */
    public void setResponsibleParty(JAXBElement<PRSSMT999002ZZResponsibleParty> value) {
        this.responsibleParty = value;
    }

    /**
     * Gets the value of the performer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the performer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerformer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PRSSMT999002ZZPerformer }
     * 
     * 
     */
    public List<PRSSMT999002ZZPerformer> getPerformer() {
        if (performer == null) {
            performer = new ArrayList<PRSSMT999002ZZPerformer>();
        }
        return this.performer;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZAuthor1 }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999002ZZAuthor1> getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZAuthor1 }{@code >}
     *     
     */
    public void setAuthor(JAXBElement<PRSSMT999002ZZAuthor1> value) {
        this.author = value;
    }

    /**
     * Gets the value of the informant property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZInformant }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999002ZZInformant> getInformant() {
        return informant;
    }

    /**
     * Sets the value of the informant property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZInformant }{@code >}
     *     
     */
    public void setInformant(JAXBElement<PRSSMT999002ZZInformant> value) {
        this.informant = value;
    }

    /**
     * Gets the value of the custodian property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZCustodian2 }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999002ZZCustodian2> getCustodian() {
        return custodian;
    }

    /**
     * Sets the value of the custodian property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZCustodian2 }{@code >}
     *     
     */
    public void setCustodian(JAXBElement<PRSSMT999002ZZCustodian2> value) {
        this.custodian = value;
    }

    /**
     * Gets the value of the inFulfillmentOf property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZInFulfillmentOf }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999002ZZInFulfillmentOf> getInFulfillmentOf() {
        return inFulfillmentOf;
    }

    /**
     * Sets the value of the inFulfillmentOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZInFulfillmentOf }{@code >}
     *     
     */
    public void setInFulfillmentOf(JAXBElement<PRSSMT999002ZZInFulfillmentOf> value) {
        this.inFulfillmentOf = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PRSSMT999002ZZReference }
     * 
     * 
     */
    public List<PRSSMT999002ZZReference> getReference() {
        if (reference == null) {
            reference = new ArrayList<PRSSMT999002ZZReference>();
        }
        return this.reference;
    }

    /**
     * Gets the value of the predecessor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predecessor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPredecessor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PRSSMT999002ZZPredecessor1 }
     * 
     * 
     */
    public List<PRSSMT999002ZZPredecessor1> getPredecessor() {
        if (predecessor == null) {
            predecessor = new ArrayList<PRSSMT999002ZZPredecessor1>();
        }
        return this.predecessor;
    }

    /**
     * Gets the value of the component property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the component property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PRSSMT999002ZZComponent4 }
     * 
     * 
     */
    public List<PRSSMT999002ZZComponent4> getComponent() {
        if (component == null) {
            component = new ArrayList<PRSSMT999002ZZComponent4>();
        }
        return this.component;
    }

    /**
     * Gets the value of the successor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZPredecessor2 }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999002ZZPredecessor2> getSuccessor() {
        return successor;
    }

    /**
     * Sets the value of the successor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999002ZZPredecessor2 }{@code >}
     *     
     */
    public void setSuccessor(JAXBElement<PRSSMT999002ZZPredecessor2> value) {
        this.successor = value;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link ActClass }
     *     
     */
    public ActClass getClassCode() {
        if (classCode == null) {
            return ActClass.ACT;
        } else {
            return classCode;
        }
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActClass }
     *     
     */
    public void setClassCode(ActClass value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the moodCode property.
     * 
     * @return
     *     possible object is
     *     {@link ActMood }
     *     
     */
    public ActMood getMoodCode() {
        if (moodCode == null) {
            return ActMood.EVN;
        } else {
            return moodCode;
        }
    }

    /**
     * Sets the value of the moodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActMood }
     *     
     */
    public void setMoodCode(ActMood value) {
        this.moodCode = value;
    }

}
