//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.24 at 04:01:25 PM CEST 
//


package org.hl7.v3.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRSS_MT001004ZZ.PertinentInformation1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PRSS_MT001004ZZ.PertinentInformation1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;choice>
 *           &lt;choice>
 *             &lt;element name="observation" type="{urn:hl7-org:v3}PRSS_MT999003ZZ.Observation"/>
 *             &lt;element name="supply" type="{urn:hl7-org:v3}PRSS_MT999003ZZ.Supply"/>
 *             &lt;element name="procedure" type="{urn:hl7-org:v3}PRSS_MT999003ZZ.Procedure"/>
 *             &lt;element name="encounter" type="{urn:hl7-org:v3}PRSS_MT999003ZZ.Encounter"/>
 *             &lt;element name="act" type="{urn:hl7-org:v3}PRSS_MT999003ZZ.Act"/>
 *             &lt;element name="financialTransaction" type="{urn:hl7-org:v3}PRSS_MT999003ZZ.FinancialTransaction"/>
 *           &lt;/choice>
 *           &lt;element name="socialeCareProvision" type="{urn:hl7-org:v3}PRSS_MT999004ZZ.SocialeCareProvision"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *       &lt;attribute name="typeCode" use="required" type="{urn:hl7-org:v3}ActRelationshipPertains" />
 *       &lt;attribute name="contextControlCode" type="{urn:hl7-org:v3}ContextControl" default="OP" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRSS_MT001004ZZ.PertinentInformation1", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "observation",
    "supply",
    "procedure",
    "encounter",
    "act",
    "financialTransaction",
    "socialeCareProvision"
})
public class PRSSMT001004ZZPertinentInformation1 {

    protected List<CS> realmCode;
    protected II typeId;
    protected List<II> templateId;
    @XmlElementRef(name = "observation", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999003ZZObservation> observation;
    @XmlElementRef(name = "supply", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999003ZZSupply> supply;
    @XmlElementRef(name = "procedure", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999003ZZProcedure> procedure;
    @XmlElementRef(name = "encounter", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999003ZZEncounter> encounter;
    @XmlElementRef(name = "act", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999003ZZAct> act;
    @XmlElementRef(name = "financialTransaction", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999003ZZFinancialTransaction> financialTransaction;
    @XmlElementRef(name = "socialeCareProvision", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
    protected JAXBElement<PRSSMT999004ZZSocialeCareProvision> socialeCareProvision;
    @XmlAttribute(name = "nullFlavor")
    protected NullFlavor nullFlavor;
    @XmlAttribute(name = "typeCode", required = true)
    protected ActRelationshipPertains typeCode;
    @XmlAttribute(name = "contextControlCode")
    protected ContextControl contextControlCode;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<CS>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTypeId(II value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<II>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the observation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZObservation }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999003ZZObservation> getObservation() {
        return observation;
    }

    /**
     * Sets the value of the observation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZObservation }{@code >}
     *     
     */
    public void setObservation(JAXBElement<PRSSMT999003ZZObservation> value) {
        this.observation = value;
    }

    /**
     * Gets the value of the supply property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZSupply }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999003ZZSupply> getSupply() {
        return supply;
    }

    /**
     * Sets the value of the supply property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZSupply }{@code >}
     *     
     */
    public void setSupply(JAXBElement<PRSSMT999003ZZSupply> value) {
        this.supply = value;
    }

    /**
     * Gets the value of the procedure property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZProcedure }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999003ZZProcedure> getProcedure() {
        return procedure;
    }

    /**
     * Sets the value of the procedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZProcedure }{@code >}
     *     
     */
    public void setProcedure(JAXBElement<PRSSMT999003ZZProcedure> value) {
        this.procedure = value;
    }

    /**
     * Gets the value of the encounter property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZEncounter }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999003ZZEncounter> getEncounter() {
        return encounter;
    }

    /**
     * Sets the value of the encounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZEncounter }{@code >}
     *     
     */
    public void setEncounter(JAXBElement<PRSSMT999003ZZEncounter> value) {
        this.encounter = value;
    }

    /**
     * Gets the value of the act property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZAct }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999003ZZAct> getAct() {
        return act;
    }

    /**
     * Sets the value of the act property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZAct }{@code >}
     *     
     */
    public void setAct(JAXBElement<PRSSMT999003ZZAct> value) {
        this.act = value;
    }

    /**
     * Gets the value of the financialTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZFinancialTransaction }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999003ZZFinancialTransaction> getFinancialTransaction() {
        return financialTransaction;
    }

    /**
     * Sets the value of the financialTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999003ZZFinancialTransaction }{@code >}
     *     
     */
    public void setFinancialTransaction(JAXBElement<PRSSMT999003ZZFinancialTransaction> value) {
        this.financialTransaction = value;
    }

    /**
     * Gets the value of the socialeCareProvision property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999004ZZSocialeCareProvision }{@code >}
     *     
     */
    public JAXBElement<PRSSMT999004ZZSocialeCareProvision> getSocialeCareProvision() {
        return socialeCareProvision;
    }

    /**
     * Sets the value of the socialeCareProvision property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PRSSMT999004ZZSocialeCareProvision }{@code >}
     *     
     */
    public void setSocialeCareProvision(JAXBElement<PRSSMT999004ZZSocialeCareProvision> value) {
        this.socialeCareProvision = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * @return
     *     possible object is
     *     {@link NullFlavor }
     *     
     */
    public NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    /**
     * Sets the value of the nullFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullFlavor }
     *     
     */
    public void setNullFlavor(NullFlavor value) {
        this.nullFlavor = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link ActRelationshipPertains }
     *     
     */
    public ActRelationshipPertains getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActRelationshipPertains }
     *     
     */
    public void setTypeCode(ActRelationshipPertains value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the contextControlCode property.
     * 
     * @return
     *     possible object is
     *     {@link ContextControl }
     *     
     */
    public ContextControl getContextControlCode() {
        if (contextControlCode == null) {
            return ContextControl.OP;
        } else {
            return contextControlCode;
        }
    }

    /**
     * Sets the value of the contextControlCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextControl }
     *     
     */
    public void setContextControlCode(ContextControl value) {
        this.contextControlCode = value;
    }

}
