package it.webred.siso.esb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-06-22T13:33:46.310+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "MedicoService", 
                  wsdlLocation = "http://localhost:8280/services/MedicoService?wsdl",
                  targetNamespace = "http://esb.siso.webred.it") 
public class MedicoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://esb.siso.webred.it", "MedicoService");
    public final static QName MedicoServiceHttpEndpoint = new QName("http://esb.siso.webred.it", "MedicoServiceHttpEndpoint");
    public final static QName MedicoServiceHttpSoap11Endpoint = new QName("http://esb.siso.webred.it", "MedicoServiceHttpSoap11Endpoint");
    public final static QName MedicoServiceHttpSoap12Endpoint = new QName("http://esb.siso.webred.it", "MedicoServiceHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8280/services/MedicoService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MedicoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "http://localhost:8280/services/MedicoService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MedicoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MedicoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MedicoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MedicoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MedicoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MedicoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MedicoServicePortType
     */
    @WebEndpoint(name = "MedicoServiceHttpEndpoint")
    public MedicoServicePortType getMedicoServiceHttpEndpoint() {
        return super.getPort(MedicoServiceHttpEndpoint, MedicoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedicoServicePortType
     */
    @WebEndpoint(name = "MedicoServiceHttpEndpoint")
    public MedicoServicePortType getMedicoServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(MedicoServiceHttpEndpoint, MedicoServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns MedicoServicePortType
     */
    @WebEndpoint(name = "MedicoServiceHttpSoap11Endpoint")
    public MedicoServicePortType getMedicoServiceHttpSoap11Endpoint() {
        return super.getPort(MedicoServiceHttpSoap11Endpoint, MedicoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedicoServicePortType
     */
    @WebEndpoint(name = "MedicoServiceHttpSoap11Endpoint")
    public MedicoServicePortType getMedicoServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(MedicoServiceHttpSoap11Endpoint, MedicoServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns MedicoServicePortType
     */
    @WebEndpoint(name = "MedicoServiceHttpSoap12Endpoint")
    public MedicoServicePortType getMedicoServiceHttpSoap12Endpoint() {
        return super.getPort(MedicoServiceHttpSoap12Endpoint, MedicoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedicoServicePortType
     */
    @WebEndpoint(name = "MedicoServiceHttpSoap12Endpoint")
    public MedicoServicePortType getMedicoServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(MedicoServiceHttpSoap12Endpoint, MedicoServicePortType.class, features);
    }

}
